name: CCIS1505 Fall 2016
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
mathjax: true
baseurl: /fall-2016
exclude: [morea]
morea_theme: spacelab
morea_navbar_items:
  #- Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
  - Schedule

# The following properties are optional.
# See the User Guide (http://morea-framework.github.io/userguide.html) for more info.

morea_course: CCIS 1505
morea_domain: http://htc-ccis1505.github.io/
#morea_google_analytics_tracking_id: "UA-63189236-5"

#morea_head_breadcrumb_link: "http://cnn.com"
#morea_head_breadcrumb_label: "CNN Site"
